name: Android Feature Publishing app to playstore

on: release

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: allex.example.org
        releaseFile: ${{ secrets.SIGNED_RELEASE_FILE}}
        track: beta
        userFraction: 0.33
        whatsNewDirectory: distribution/whatsnew
        mappingFile: app/build/outputs/mapping/release/mapping.txt

      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
